import { Voucher } from '../types';

/**
 * Generates a unique voucher code based on a capital-letter-friendly alphabet.
 */
export function generateVoucherCode(
  prefix: string,
  totalLength: number,
  usedCodes: Record<string, boolean>
): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const remainingLength = Math.max(0, totalLength - prefix.length);
  const maxAttempts = 100;
  
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    let code = prefix.toUpperCase();
    for (let i = 0; i < remainingLength; i++) {
       code += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    if (!usedCodes[code]) {
      return code;
    }
  }
  throw new Error('Could not generate a unique code. Try starting with a different prefix or increasing total length.');
}

/**
 * Formats time in minutes for human display
 */
export function formatTimeForDisplay(minutes: number): string {
  if (minutes >= 1440) {
    const days = Math.floor(minutes / 1440);
    return `${days} day${days > 1 ? 's' : ''}`;
  } else if (minutes >= 60) {
    const hours = Math.floor(minutes / 60);
    return `${hours} hour${hours > 1 ? 's' : ''}`;
  }
  return `${minutes} min${minutes > 1 ? 's' : ''}`;
}

/**
 * Connects the list of generated vouchers to RouterOS compatible configuration script .rsc.
 */
export function generateMikroTikScript(vouchers: Voucher[], hotspotName: string): string {
  if (vouchers.length === 0) return '';
  let script = `# Generated by MikroTik Voucher Generator\n`;
  script += `# Hotspot Name: ${hotspotName}\n`;
  script += `# Import using command: /import file-name=<filename>.rsc\n\n`;
  
  vouchers.forEach((v) => {
    const profileParam = v.profile ? ` profile="${v.profile}"` : '';
    // Format is compatible with MikroTik RouterOS CLI user addition
    script += `/ip hotspot user add name="${v.code}" limit-uptime=${v.time}m${profileParam} comment="${v.validity}m,${v.amount},${hotspotName}" disabled=no\n`;
  });
  
  return script;
}

/**
 * Secure serial hashing algorithm mimicking original code to create activation keys.
 */
export function generatePortalKeyFromSerial(serial: string): string | null {
  if (!serial || serial.trim() === '') return null;
  
  const serialTrimmed = serial.trim().toUpperCase();
  let hash = 0;
  for (let i = 0; i < serialTrimmed.length; i++) {
    const char = serialTrimmed.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32bit integer
  }
  hash = Math.abs(hash);
  
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = '';
  let seed = hash;
  
  for (let i = 0; i < 20; i++) {
    seed = (seed * 1103515245 + 12345) & 0x7fffffff;
    result += chars.charAt(seed % chars.length);
  }
  
  return (
    result.substring(0, 5) + '-' + 
    result.substring(5, 10) + '-' + 
    result.substring(10, 15) + '-' + 
    result.substring(15, 20)
  );
}

/**
 * Prepares CSV content download
 */
export function exportToCSVContent(vouchers: Voucher[]): string {
  let csv = 'Code,Amount(pesos),Validity(Minutes),Time(Minutes),Profile\n';
  vouchers.forEach((v) => {
    const profileText = v.profile ? v.profile : 'default';
    csv += `${v.code},${v.amount},${v.validity},${v.time},${profileText}\n`;
  });
  return csv;
}
